Traceback (most recent call last):
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/joshredmond/anaconda3/envs/GIScienceWorkshop/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
center = (53.8008, -1.5491)
m = Map(center=center, zoom=12)

# First, we will load the spectral indices data from the raster files. 

ndvi_array = rio.open('data/leeds_NDVI_aug_highres.tif').read()
ndwi_array = rio.open('data/leeds_NDWI_aug_highres.tif').read()
ndbi_array = rio.open('data/leeds_NDBI_aug_highres.tif').read()

# All three of these arrays have the same shape, so we can use the shape and extent of one of them to define the extent of air temperature data.

image_extent = rio.open('data/leeds_NDVI_aug_highres.tif').bounds
SW = (image_extent.bottom, image_extent.left)
NE = (image_extent.top, image_extent.right)
bounds_tuple = (SW, NE)

# Now, lets create the airtemperature array which holds the data
airtemp_array = model_airtemp(3, ndvi_array, ndbi_array, ndwi_array)

from PIL import Image

array = np.moveaxis(airtemp_array, 0, -1)
nan_mask = ~np.isnan(array) * 1 
nan_mask *= 255
array_min = np.nanmin(array)

nan_mask = nan_mask.astype(np.uint8)
array = np.nan_to_num(array)


array_max = np.max(array)
array = np.clip((array - array_min) / (array_max - array_min) * 255, 0, 255)
array = array.astype(np.uint8)
os.remove("airtemp.png")

image = Image.fromarray(np.squeeze(np.stack([array, array, array, nan_mask], axis=-1)), mode="RGBA")
image.save('airtemp.png')


# Now we can add the image to the map
image_layer = ImageOverlay(url="airtemp.png", bounds=bounds_tuple)
m.add_layer(image_layer)
display(m)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 35[0m
[1;32m     33[0m array [38;5;241m=[39m np[38;5;241m.[39mclip((array [38;5;241m-[39m array_min) [38;5;241m/[39m (array_max [38;5;241m-[39m array_min) [38;5;241m*[39m [38;5;241m255[39m, [38;5;241m0[39m, [38;5;241m255[39m)
[1;32m     34[0m array [38;5;241m=[39m array[38;5;241m.[39mastype(np[38;5;241m.[39muint8)
[0;32m---> 35[0m [43mos[49m[38;5;241;43m.[39;49m[43mremove[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mairtemp.png[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     37[0m image [38;5;241m=[39m Image[38;5;241m.[39mfromarray(np[38;5;241m.[39msqueeze(np[38;5;241m.[39mstack([array, array, array, nan_mask], axis[38;5;241m=[39m[38;5;241m-[39m[38;5;241m1[39m)), mode[38;5;241m=[39m[38;5;124m"[39m[38;5;124mRGBA[39m[38;5;124m"[39m)
[1;32m     38[0m image[38;5;241m.[39msave([38;5;124m'[39m[38;5;124mairtemp.png[39m[38;5;124m'[39m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'airtemp.png'

